server:
  port: 8083
spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: 123321!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
    register-with-eureka: true
    fetch-registry: true
mybatis:
  type-aliases-package: com.humor.domain.pojo
  mapper-locations: classpath:mappers/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



