server:
  port: 8083
  servlet:
    context-path: /product-server
spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: 123321!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

mybatis:
  type-aliases-package: com.humor.domain.pojo
  mapper-locations: classpath:mappers/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



