server:
  port: 8083
  servlet:
    context-path: /product-server
spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.18.193.77:3306/product_db
    username: root
    password: dzm123%*
  jpa:
    show-sql: true
    properties:
          hibernate:
            hbm2ddl:
              auto: update
  devtools:
    restart:
      enabled: true
      exclude: static/*

eureka:
  client:
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
