server:
  port: 8083
spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: 123321!
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

mybatis:
  type-aliases-package: com.humor.domain.pojo
  mapper-locations: classpath:mappers/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


swagger:
  basePackage: com.humor.user.controller
  title: 微服务、分布式实践
  description: 笑而不语，痛而不言
  contact:
    name: humor
    email: guxingying@live.cn
    url: http://localhost:8089
