server:
  port: 8086
spring:
  application:
    name: common-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123321!
    url: jdbc:mysql://localhost:3306/common_db
  mail:
    host: pop.qq.com
    username: 943456477@qq.com
    password: Love&Home=999
    default-encoding: utf-8

mail:
  fromMail:
    addr: 943456477@qq.com


swagger:
  basePackage: com.humor.user.controller
  title: 微服务、分布式实践
  description: 笑而不语，痛而不言
  contact:
    name: humor
    email: guxingying@live.cn
    url: http://localhost:8089

