server:
  port: 8082
spring:
  application:
    name: order-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 123321!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
    register-with-eureka: true
    fetch-registry: true


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.humor.pojo

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql






