server:
  port: 8082
  servlet:
    context-path: /order-server
spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.18.193.77:3306/order_db
    username: root
    password: dzm123%*
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
