server:
  port: 8081
spring:
  application:
    name: cart-server
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123321!
    url: jdbc:mysql://localhost:3306/cart_db

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.humor.pojo

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level: com.codingapi=debug


swagger:
  basePackage: com.humor.user.controller
  title: 微服务、分布式实践
  description: 笑而不语，痛而不言
  contact:
    name: humor
    email: guxingying@live.cn
    url: http://localhost:8089






