server:
  port: 8081
  servlet:
    context-path: /cart-server
spring:
  application:
    name: cart-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dzm123%*
    url: jdbc:mysql://119.18.193.77:3306/cart_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  devtools:
    restart:
      enabled: true
      exclude: static/*

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.springcloud.cn/eureka

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: false
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: false
  client:
    default-config: default

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.humor.cart.service.api.ProductService: debug
